/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiEventsIndexRouteImport } from './routes/api/events/index'
import { Route as ApiDonationsIndexRouteImport } from './routes/api/donations/index'
import { Route as ApiImagesSplatRouteImport } from './routes/api/images/$'
import { Route as ApiEventsIdRouteImport } from './routes/api/events/$id'
import { Route as ApiDonationsSeedRouteImport } from './routes/api/donations/seed'
import { Route as ApiDonationsIdRouteImport } from './routes/api/donations/$id'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIndexRoute = ApiEventsIndexRouteImport.update({
  id: '/api/events/',
  path: '/api/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsIndexRoute = ApiDonationsIndexRouteImport.update({
  id: '/api/donations/',
  path: '/api/donations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesSplatRoute = ApiImagesSplatRouteImport.update({
  id: '/api/images/$',
  path: '/api/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIdRoute = ApiEventsIdRouteImport.update({
  id: '/api/events/$id',
  path: '/api/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsSeedRoute = ApiDonationsSeedRouteImport.update({
  id: '/api/donations/seed',
  path: '/api/donations/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationsIdRoute = ApiDonationsIdRouteImport.update({
  id: '/api/donations/$id',
  path: '/api/donations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/donations/$id': typeof ApiDonationsIdRoute
  '/api/donations/seed': typeof ApiDonationsSeedRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/donations/': typeof ApiDonationsIndexRoute
  '/api/events/': typeof ApiEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/donations/$id': typeof ApiDonationsIdRoute
  '/api/donations/seed': typeof ApiDonationsSeedRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/donations': typeof ApiDonationsIndexRoute
  '/api/events': typeof ApiEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/get-involved': typeof GetInvolvedRoute
  '/programs': typeof ProgramsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/donations/$id': typeof ApiDonationsIdRoute
  '/api/donations/seed': typeof ApiDonationsSeedRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/images/$': typeof ApiImagesSplatRoute
  '/api/donations/': typeof ApiDonationsIndexRoute
  '/api/events/': typeof ApiEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/get-involved'
    | '/programs'
    | '/api/upload'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/verify'
    | '/api/donations/$id'
    | '/api/donations/seed'
    | '/api/events/$id'
    | '/api/images/$'
    | '/api/donations/'
    | '/api/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/get-involved'
    | '/programs'
    | '/api/upload'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/verify'
    | '/api/donations/$id'
    | '/api/donations/seed'
    | '/api/events/$id'
    | '/api/images/$'
    | '/api/donations'
    | '/api/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/get-involved'
    | '/programs'
    | '/api/upload'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/verify'
    | '/api/donations/$id'
    | '/api/donations/seed'
    | '/api/events/$id'
    | '/api/images/$'
    | '/api/donations/'
    | '/api/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ProgramsRoute: typeof ProgramsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiDonationsIdRoute: typeof ApiDonationsIdRoute
  ApiDonationsSeedRoute: typeof ApiDonationsSeedRoute
  ApiEventsIdRoute: typeof ApiEventsIdRoute
  ApiImagesSplatRoute: typeof ApiImagesSplatRoute
  ApiDonationsIndexRoute: typeof ApiDonationsIndexRoute
  ApiEventsIndexRoute: typeof ApiEventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/': {
      id: '/api/events/'
      path: '/api/events'
      fullPath: '/api/events/'
      preLoaderRoute: typeof ApiEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/': {
      id: '/api/donations/'
      path: '/api/donations'
      fullPath: '/api/donations/'
      preLoaderRoute: typeof ApiDonationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$': {
      id: '/api/images/$'
      path: '/api/images/$'
      fullPath: '/api/images/$'
      preLoaderRoute: typeof ApiImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$id': {
      id: '/api/events/$id'
      path: '/api/events/$id'
      fullPath: '/api/events/$id'
      preLoaderRoute: typeof ApiEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/seed': {
      id: '/api/donations/seed'
      path: '/api/donations/seed'
      fullPath: '/api/donations/seed'
      preLoaderRoute: typeof ApiDonationsSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/$id': {
      id: '/api/donations/$id'
      path: '/api/donations/$id'
      fullPath: '/api/donations/$id'
      preLoaderRoute: typeof ApiDonationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ProgramsRoute: ProgramsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiDonationsIdRoute: ApiDonationsIdRoute,
  ApiDonationsSeedRoute: ApiDonationsSeedRoute,
  ApiEventsIdRoute: ApiEventsIdRoute,
  ApiImagesSplatRoute: ApiImagesSplatRoute,
  ApiDonationsIndexRoute: ApiDonationsIndexRoute,
  ApiEventsIndexRoute: ApiEventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
